version: '3.1'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-invite-me
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inviteme
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
